name: windows

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'DEVELOPNOTE.md'
      - 'CHANGELOG.md'
      - '.readthedocs.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'DEVELOPNOTE.md'
      - 'CHANGELOG.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          arch: win64_mingw
          version: '6.5.3'
          modules: 'qt5compat'
          aqtversion: ==3.1.7

      - name: Build all
        run: |
          git fetch --tags --force
          git describe --always --long --abbrev=10 --tags | ./tools/awk/awk.exe '{print \"\\\"\"$0\"\\\"\"}'  > git_tag.inc
          ./tools/sed/sed.exe -i "s/git_tag.inc/git_tag.ci.inc/g" evt3_parse.pro
          qmake evt3_parse.pro -spec win32-g++
          mingw32-make -j8
          windeployqt --dir .\output ./build_release/out/evt3_parse.exe
          cp ./build_release/out/evt3_parse.exe ./output/evt3_parse.exe
          Compress-Archive -Path .\output\* -DestinationPath evt3_parse.zip

      - name: Upload build asserts
        uses: actions/upload-artifact@v4
        with:
          name: evt3_parse_windows
          path: |
            ./evt3_parse.zip
